#!/bin/bash

rootdir=`dirname "$(readlink -f "$0")"`
. ${rootdir}/../general/boilerplate.sh
. ${rootdir}/../ssh/ssh.sh

redis_cfg=$1

. $redis_cfg #for redis config such as redis_local_port

portforward $redis_local_port $redis_remote_host $redis_remote_port redis-cli -c -h localhost -p $redis_local_port
