#!/usr/bin/env bash

rootdir=`dirname "$(readlink -f "$0")"`
. ${rootdir}/../general/boilerplate.sh

recursive() {
    local parent_dir=`realpath $1`
    local cmd="${@:2}"
    for subdir in `ls -d ${parent_dir}/*/`; do
        echo $subdir >&2
        cd $subdir
        $cmd || echo "failed to perform $cmd" >&2
    done
}

usage() {
  programname=$(basename $1)
  echo "Usage: $programname parent_dir command.."
  echo "  Perform command in each child directory of parent_dir."
}

main() {
  if [ $# == 1 ] && ([[ $1 == "--help" ||  $1 == "-h" ]]); then
    usage $0
  elif [ $# -ge 2 ]; then
    recursive "$@"
  else
    usage $0
    exit 1
  fi
}

main "$@"
