#!/bin/bash

rootdir=`dirname "$(readlink -f "$0")"`
. ${rootdir}/../general/boilerplate.sh
. ${rootdir}/../ssh/ssh.sh

mongo_cfg=$1

. $mongo_cfg #for mongo config such as mongo_local_port

portforward $mongo_local_port $mongo_remote_host $mongo_remote_port mongo --sslAllowInvalidHostnames --ssl --sslCAFile $mongo_ssl_ca_file --username ${mongo_user} --password ${mongo_pswd}
